################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productionDescription: Digitally transform your payment process with certified ERP integration to improve working capital and increase efficiencies. SnapPay from Fiserv, integrates with popular ERP solutions and shopping cart solutions to serve the holistic B2B payment needs of enterprise-size businesses.
  whoIsItFor: SnapPay application is built to serve medium and large merchants for enabling payments on both accounts receivables and payables side of business. It also serves government sector.

  image: 
    link: "/assets/images/Fiserv_Logo.jpg"
    altText: Fiserv SnapPay™
featuredFeatures:
  - title: Enable Payments for external application
    description:  This set of API enables our merchants to integrate payment processing with any application of their choice. Their customers can make payments using credit card or ACH.
    tags: ["REPLACEME", "REPLACEME", "REPLACEME"]
    bullets: ["REPLACEME", "REPLACEME" ]  
    relatedDocs:
      - relatedDoc: 
        title: Getting Started
        description: Getting started with SnapPay APIs.
        link: "/docs/getting-started.md"
      - relatedDoc: 
        title: APIs with User Interaction
        description: These set of APIs require user interaction.
        link: "/docs/apis-with-user-interaction.md"
      - relatedDoc: 
        title: APIs without User Interaction
        description: These set of APIs does not require user interaction.
        link: "/docs/apis-without-user-interaction.md"
    relatedAPIs:
      - relatedAPI: 
        title: Get Request ID API
        description: This API prepares SnapPay with the information required to properly display SnapPay from within an iFrame or as a full page for user interaction to Authorize, Charge or Tokenize a credit card or ACH account.
        type: "post"        
        path: "/api/Interop/GetRequestID"
      - relatedAPI: 
        title: Get Payment Details API
        description: This API returns the results of the GetRequestID and iFrame interaction to allow for further business processing like completing the order creation process on an eCommerce site after successful card authorization.
        type: "post"        
        path: "/api/Interop/GetPaymentDetails"
  - title: Seamlessly Integrate With Leading ERP Platforms
    description: Extend the accounts receivable and accounts payable process beyond the ERP into the extended supply chain. Facilitate the movement of funds securely and seamlessly. We offer an open API platform and the ability to integrate with any ERP.
    tags: ["REPLACEME", "REPLACEME", "REPLACEME"]
    bullets: ["REPLACEME", "REPLACEME" ]  
  - title: Streamline Invoice-to-Pay Processes
    description: Now you can move money and information between buyers and suppliers digitally and securely, with a comprehensive, multichannel payment automation solution from Fiserv.
    tags: ["REPLACEME", "REPLACEME", "REPLACEME"]
    bullets: ["REPLACEME", "REPLACEME" ]  
